// <auto-generated />
using System;
using DurianQR.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DurianQR.API.Migrations
{
    [DbContext(typeof(DurianQRContext))]
    [Migration("20260130193713_HarvestWorkflow")]
    partial class HarvestWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DurianQR.API.Models.BatchHarvestRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContributedWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestID");

                    b.HasIndex("BatchID", "RequestID")
                        .IsUnique();

                    b.ToTable("BatchHarvestRequests");
                });

            modelBuilder.Entity("DurianQR.API.Models.BatchQRCode", b =>
                {
                    b.Property<int>("QRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QRID"));

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("QRImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.HasKey("QRID");

                    b.HasIndex("BatchID");

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("DurianQR.API.Models.Chemical", b =>
                {
                    b.Property<int>("ChemicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChemicalID"));

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PHI_Days")
                        .HasColumnType("int");

                    b.Property<string>("TargetMarket")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ChemicalID");

                    b.HasIndex("ChemicalName");

                    b.ToTable("Chemicals");

                    b.HasData(
                        new
                        {
                            ChemicalID = 1,
                            ActiveIngredient = "Abamectin 1.8%",
                            ChemicalName = "Abamectin",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(1011),
                            IsBanned = false,
                            PHI_Days = 14,
                            TargetMarket = "VN,CN"
                        },
                        new
                        {
                            ChemicalID = 2,
                            ActiveIngredient = "Chlorpyrifos 48%",
                            ChemicalName = "Chlorpyrifos",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(2037),
                            IsBanned = true,
                            PHI_Days = 21,
                            TargetMarket = "EU"
                        },
                        new
                        {
                            ChemicalID = 3,
                            ActiveIngredient = "Imidacloprid 10%",
                            ChemicalName = "Imidacloprid",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(2040),
                            IsBanned = false,
                            PHI_Days = 14,
                            TargetMarket = "VN,CN"
                        },
                        new
                        {
                            ChemicalID = 4,
                            ActiveIngredient = "Mancozeb 80%",
                            ChemicalName = "Mancozeb",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(2041),
                            IsBanned = false,
                            PHI_Days = 7,
                            TargetMarket = "VN"
                        },
                        new
                        {
                            ChemicalID = 5,
                            ActiveIngredient = "Thiamethoxam 25%",
                            ChemicalName = "Thiamethoxam",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(2043),
                            IsBanned = true,
                            PHI_Days = 14,
                            TargetMarket = "EU"
                        });
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.Property<int>("TreeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FarmID")
                        .HasColumnType("int");

                    b.Property<int?>("PlantingYear")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TreeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Variety")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TreeID");

                    b.HasIndex("FarmID");

                    b.HasIndex("TreeCode");

                    b.ToTable("DurianTrees");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.Property<int>("FarmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FarmID"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FarmID");

                    b.HasIndex("UserID");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("DurianQR.API.Models.FarmingLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ChemicalID")
                        .HasColumnType("int");

                    b.Property<string>("ChemicalUsed")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("DosageAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAutoValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SafeAfterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SafetyDays")
                        .HasColumnType("int");

                    b.Property<int>("TreeID")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("LogID");

                    b.HasIndex("ActivityType");

                    b.HasIndex("ChemicalID");

                    b.HasIndex("LogDate");

                    b.HasIndex("TreeID");

                    b.ToTable("FarmingLogs");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ApprovalNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CheckedInBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EstimatedQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ExpectedHarvestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GradeA_Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GradeB_Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GradeC_Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PHICheckResult")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SafeAfterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TreeID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("ExpectedHarvestDate");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TreeID");

                    b.HasIndex("UserID");

                    b.ToTable("HarvestRequests");
                });

            modelBuilder.Entity("DurianQR.API.Models.ProductBatch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ExportStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("GradeA_Weight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GradeB_Weight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GradeC_Weight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("PackingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QualityGrade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TargetMarket")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("TotalWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("BatchID");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("ExportStatus");

                    b.HasIndex("WarehouseID");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("DurianQR.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DurianQR.API.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("WarehouseID");

                    b.HasIndex("ManagerID")
                        .IsUnique();

                    b.HasIndex("WarehouseName");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseID = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(6870),
                            Location = "Huyện Krông Pắk, Đắk Lắk",
                            WarehouseName = "HTX Krông Pắk"
                        },
                        new
                        {
                            WarehouseID = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 37, 12, 586, DateTimeKind.Utc).AddTicks(7750),
                            Location = "Huyện Cư M'gar, Đắk Lắk",
                            WarehouseName = "HTX Cư M'gar"
                        });
                });

            modelBuilder.Entity("DurianQR.API.Models.BatchHarvestRequest", b =>
                {
                    b.HasOne("DurianQR.API.Models.ProductBatch", "Batch")
                        .WithMany("HarvestRequests")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DurianQR.API.Models.HarvestRequest", "HarvestRequest")
                        .WithMany("BatchRequests")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("HarvestRequest");
                });

            modelBuilder.Entity("DurianQR.API.Models.BatchQRCode", b =>
                {
                    b.HasOne("DurianQR.API.Models.ProductBatch", "Batch")
                        .WithMany("QRCodes")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.HasOne("DurianQR.API.Models.Farm", "Farm")
                        .WithMany("Trees")
                        .HasForeignKey("FarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.HasOne("DurianQR.API.Models.User", "User")
                        .WithMany("Farms")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DurianQR.API.Models.FarmingLog", b =>
                {
                    b.HasOne("DurianQR.API.Models.Chemical", "Chemical")
                        .WithMany("FarmingLogs")
                        .HasForeignKey("ChemicalID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DurianQR.API.Models.DurianTree", "Tree")
                        .WithMany("FarmingLogs")
                        .HasForeignKey("TreeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestRequest", b =>
                {
                    b.HasOne("DurianQR.API.Models.DurianTree", "Tree")
                        .WithMany("HarvestRequests")
                        .HasForeignKey("TreeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DurianQR.API.Models.User", "Farmer")
                        .WithMany("HarvestRequests")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("DurianQR.API.Models.ProductBatch", b =>
                {
                    b.HasOne("DurianQR.API.Models.Warehouse", "Warehouse")
                        .WithMany("ProductBatches")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DurianQR.API.Models.Warehouse", b =>
                {
                    b.HasOne("DurianQR.API.Models.User", "Manager")
                        .WithOne("ManagedWarehouse")
                        .HasForeignKey("DurianQR.API.Models.Warehouse", "ManagerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DurianQR.API.Models.Chemical", b =>
                {
                    b.Navigation("FarmingLogs");
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.Navigation("FarmingLogs");

                    b.Navigation("HarvestRequests");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestRequest", b =>
                {
                    b.Navigation("BatchRequests");
                });

            modelBuilder.Entity("DurianQR.API.Models.ProductBatch", b =>
                {
                    b.Navigation("HarvestRequests");

                    b.Navigation("QRCodes");
                });

            modelBuilder.Entity("DurianQR.API.Models.User", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("HarvestRequests");

                    b.Navigation("ManagedWarehouse");
                });

            modelBuilder.Entity("DurianQR.API.Models.Warehouse", b =>
                {
                    b.Navigation("ProductBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
