// <auto-generated />
using System;
using DurianQR.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DurianQR.API.Migrations
{
    [DbContext(typeof(DurianQRContext))]
    partial class DurianQRContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DurianQR.API.Models.BatchQRCode", b =>
                {
                    b.Property<int>("QRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QRID"));

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("QRImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.HasKey("QRID");

                    b.HasIndex("BatchID");

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("DurianQR.API.Models.Chemical", b =>
                {
                    b.Property<int>("ChemicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChemicalID"));

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PHI_Days")
                        .HasColumnType("int");

                    b.Property<string>("TargetMarket")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ChemicalID");

                    b.HasIndex("ChemicalName");

                    b.ToTable("Chemicals");

                    b.HasData(
                        new
                        {
                            ChemicalID = 1,
                            ActiveIngredient = "Abamectin 1.8%",
                            ChemicalName = "Abamectin",
                            CreatedAt = new DateTime(2026, 1, 30, 16, 40, 25, 4, DateTimeKind.Utc).AddTicks(9553),
                            IsBanned = false,
                            PHI_Days = 14,
                            TargetMarket = "VN,CN"
                        },
                        new
                        {
                            ChemicalID = 2,
                            ActiveIngredient = "Chlorpyrifos 48%",
                            ChemicalName = "Chlorpyrifos",
                            CreatedAt = new DateTime(2026, 1, 30, 16, 40, 25, 5, DateTimeKind.Utc).AddTicks(450),
                            IsBanned = true,
                            PHI_Days = 21,
                            TargetMarket = "EU"
                        },
                        new
                        {
                            ChemicalID = 3,
                            ActiveIngredient = "Imidacloprid 10%",
                            ChemicalName = "Imidacloprid",
                            CreatedAt = new DateTime(2026, 1, 30, 16, 40, 25, 5, DateTimeKind.Utc).AddTicks(452),
                            IsBanned = false,
                            PHI_Days = 14,
                            TargetMarket = "VN,CN"
                        },
                        new
                        {
                            ChemicalID = 4,
                            ActiveIngredient = "Mancozeb 80%",
                            ChemicalName = "Mancozeb",
                            CreatedAt = new DateTime(2026, 1, 30, 16, 40, 25, 5, DateTimeKind.Utc).AddTicks(453),
                            IsBanned = false,
                            PHI_Days = 7,
                            TargetMarket = "VN"
                        },
                        new
                        {
                            ChemicalID = 5,
                            ActiveIngredient = "Thiamethoxam 25%",
                            ChemicalName = "Thiamethoxam",
                            CreatedAt = new DateTime(2026, 1, 30, 16, 40, 25, 5, DateTimeKind.Utc).AddTicks(455),
                            IsBanned = true,
                            PHI_Days = 14,
                            TargetMarket = "EU"
                        });
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.Property<int>("TreeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FarmID")
                        .HasColumnType("int");

                    b.Property<int?>("PlantingYear")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TreeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Variety")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TreeID");

                    b.HasIndex("FarmID");

                    b.HasIndex("TreeCode");

                    b.ToTable("DurianTrees");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.Property<int>("FarmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FarmID"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FarmID");

                    b.HasIndex("UserID");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("DurianQR.API.Models.FarmingLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<string>("ChemicalUsed")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("DosageAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAutoValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SafeAfterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SafetyDays")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("LogID");

                    b.HasIndex("BatchID");

                    b.HasIndex("LogDate");

                    b.ToTable("FarmingLogs");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestBatch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<DateTime?>("ActualHarvest")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpectedHarvest")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FloweringDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QualityGrade")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TreeID")
                        .HasColumnType("int");

                    b.HasKey("BatchID");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("TreeID");

                    b.ToTable("HarvestBatches");
                });

            modelBuilder.Entity("DurianQR.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DurianQR.API.Models.BatchQRCode", b =>
                {
                    b.HasOne("DurianQR.API.Models.HarvestBatch", "Batch")
                        .WithMany("QRCodes")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.HasOne("DurianQR.API.Models.Farm", "Farm")
                        .WithMany("Trees")
                        .HasForeignKey("FarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.HasOne("DurianQR.API.Models.User", "User")
                        .WithMany("Farms")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DurianQR.API.Models.FarmingLog", b =>
                {
                    b.HasOne("DurianQR.API.Models.HarvestBatch", "Batch")
                        .WithMany("FarmingLogs")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestBatch", b =>
                {
                    b.HasOne("DurianQR.API.Models.DurianTree", "Tree")
                        .WithMany("Batches")
                        .HasForeignKey("TreeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("DurianQR.API.Models.DurianTree", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("DurianQR.API.Models.Farm", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("DurianQR.API.Models.HarvestBatch", b =>
                {
                    b.Navigation("FarmingLogs");

                    b.Navigation("QRCodes");
                });

            modelBuilder.Entity("DurianQR.API.Models.User", b =>
                {
                    b.Navigation("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
